### ISSUE TITLE
search.json should be in the sitemap! error

### ISSUE THREAD

**Issue by meleyal** [middleman/middleman#1898]
I have the following directory structure:

```
- /source
-- ...
-- search.json.erb
```

Where `search.json.erb` is used to build a client search search index.

This worked in 3.4.0, but with 3.4.1 I get the following error:
https://gist.github.com/meleyal/f6c8b05f3241ba4f2eb52a484e8d56f3

I think this may be related to https://github.com/middleman/middleman/issues/1590.

Middleman: 3.4.1
Ruby: 2.2.4
OS: Max OS X 10.11.4

**Comment by tdreyno** [comment]
It looks like the asset_hash extension is trying to rename `search.json` which is probably not what you want. Can you see if it works without that extension active?

**Comment by meleyal** [comment]
I can confirm it works without `asset_hash` but we actually need asset hashing for `search.json`.

**Comment by tdreyno** [comment]
So, you've added `.json` to the list of valid hash extensions?

**Comment by meleyal** [comment]
Yes, in `config.rb`:
```ruby
activate :asset_hash do |asset_hash|
  asset_hash.exts = asset_hash.exts + %w(.json)
end
```

**Comment by tdreyno** [comment]
And then, that json file is a string in some JS somewhere to load it? If you remove that reference in the JS, does it run without the error?

**Comment by meleyal** [comment]
Yes `search.json` is referenced in a search form:
```html
<form class="navbar-form navbar-left" role="search" action="<%= url_for('/search.json') %>">
  ...
</form>
```

Now I'm seeing a different error:
```shell
.../search.json.erb:22:in `url_to_title': undefined method `[]' for nil:NilClass (NoMethodError)
```

`search.json.erb`:
```ruby
<%

filter_md = -> r {
  File.extname(r.source_file) == '.md' &&
  File.basename(r.source_file) != 'index.md'
}

to_entry = -> r do
  { id: r.url,
    title: url_to_title(r.url),
    body: File.read(r.source_file),
    path: r.url }
end

def url_to_title(url)
  url = url.split('/').pop || ""
  data.pages.map do |s|
    s.pages.map { |p| { url:  p["url"], title: p["title"] } }
  end
  .flatten
  .select { |p| p[:url] == url }
  .first[:title]
end

index = sitemap.resources
  .select(&filter_md)
  .map(&to_entry)

%>

<%= index.to_json %>
```

**Comment by tdreyno** [comment]
I think that might be unrelated. But I'll try to build a test case around the above example (adding json to files and referencing in a form)
