### ISSUE TITLE
.js.coffee.erb file fails to build on 3.0.9

### ISSUE THREAD

**Issue by barvian** [middleman/middleman#731]
I'm having some issues with a simple .js.coffee.erb file:

``` coffeescript
$(".page-head").backstretch "<%= asset_url 'imageFile.png', images_dir %>"
```

It works great on the server but upon building, the compiled .js file contains this:

``` javascript
throw Error("NoMethodError: undefined method `sub' for nil:NilClass\n  (in /mb.js.coffee.erb)");
```

Any ideas?

Thanks,

Max
