### ISSUE TITLE
:locals method doesn't work as expected

### ISSUE THREAD

**Issue by hanno-sergeitatarinov** [middleman/middleman#1981]
I have the page: `page.html.erb,` and the partial: `_contactForm.erb`.

In the partial I have the title element `<span><%= thetitle %></span>`.

I'm including the partial on the page and passing custom text into the title: `<%= partial(:contactForm, :locals => { :thetitle => 'Make Contact' }) %>`

The error I'm getting: 

> NameError at /products-pricing
> undefined local variable or method `thetitle' for #Middleman::Application:0x70123295342540

What might be causing this issue?
## 
- Ruby version: 2.2.1
- Middleman version: 3.4.0 
- OS version: OS X El Capitan

**Comment by tdreyno** [comment]
While I'd love for everyone to be on Middleman 4, it should be safe for you to update to 3.4.1 atleast and see if that helps.

**Comment by joshwayne** [comment]
Still getting this bug in version 4.2.1

Page layout:
`<%= partial("test_partial", :locals => { :title => "Title Here" }) %>`

Partial content `_test_partial.erb`:
```
<div>
    <%= title %>
</div>
```

Receiving the error `undefined local variable or method 'title' for #<#<Class:0x007fabb8dbb260>:0x007fabb623f988>`

---

- Ruby version: 2.4.1p111
- Middleman version: 4.2.1

**Comment by tomsabin** [comment]
@joshwayne, we were having the same problem when upgrading from 3.4.3 to 4.2.1 and have managed to solve it by monkey patching the `partial` method.

This fix is relatively simple, as it is this line which was causing the problem for us: https://github.com/middleman/middleman/blob/09f3be9aba1ee07d5afcf8601e368f1e8fa8c524/middleman-core/lib/middleman-core/core_extensions/default_helpers.rb#L282

It sounds like you have a similar problem. We've overwritten the line above to use the [`Middleman::Util::EnhancedHash.new`](https://github.com/unboxed/unboxed.co/blob/40024eb283c893c2e07a941745fda4c9fd75dc27/helpers/render_partial.rb#L26) object instead of a Ruby Hash. Here's the commit which introduces the monkey patch as a helper: https://github.com/unboxed/unboxed.co/pull/442/commits/40024eb283c893c2e07a941745fda4c9fd75dc27. 

Hope that it works for you too.
