### ISSUE TITLE
accessing /__middleman/config/ fails after commit c7a4618

### ISSUE THREAD

**Issue by SugoiDev** [middleman/middleman#1787]
The [commit (c7a4618)](https://github.com/middleman/middleman/commit/c7a46181664bf47e5dd149932d2f0302e212030a#diff-6d1122cbf533d9850ccc6eb4ab9ef224) changed line 109 on `extensions.rb` from
`@auto_activate.values.map(&:to_a).flatten.map(&:name)`
to
`@auto_activate.values.map(&:to_a).flat_map(&:name)`

This causes the following error when accessing the page config list page:
```
NoMethodError at /__middleman/config/
undefined method `name' for #<Array:0x9e34708>
[...]middleman-core-4.1.0/lib/middleman-core/extensions.rb:109:in `each'
...
```

Reverting line 109 to

`@auto_activate.values.map(&:to_a).flatten.map(&:name)`

solves this.

I'm not sending a pull request because I didn't dig to understand the implications (if any) of reverting this.

**Comment by tdreyno** [comment]
Shiiiiiit, whoops :) Fixing now

**Comment by SugoiDev** [comment]
Awesome!
