### ISSUE TITLE
Undefined method `cattr_accessor'

### ISSUE THREAD

**Issue by sethvargo** [middleman/middleman#1469]
It looks like Middleman + latest Redcarpet are not playing nicely together:

```
/Users/sethvargo/.gem/ruby/2.2.0/gems/middleman-core-3.3.9/lib/middleman-core/renderers/redcarpet.rb:51:in `<class:MiddlemanRedcarpetHTML>': undefined method `cattr_accessor' for Middleman::Renderers::MiddlemanRedcarpetHTML:Class (NoMethodError)
	from /Users/sethvargo/.gem/ruby/2.2.0/gems/middleman-core-3.3.9/lib/middleman-core/renderers/redcarpet.rb:50:in `<module:Renderers>'
	from /Users/sethvargo/.gem/ruby/2.2.0/gems/middleman-core-3.3.9/lib/middleman-core/renderers/redcarpet.rb:4:in `<module:Middleman>'
	from /Users/sethvargo/.gem/ruby/2.2.0/gems/middleman-core-3.3.9/lib/middleman-core/renderers/redcarpet.rb:3:in `<top (required)>'
```

- Middleman 3.3.9
- Redcarpet 3.2.2

I don't know who is supposed to be defining `cattr_accessor` (maybe activesupport?), but it looks like it is not longer required in AS by default now?

**Comment by Arcovion** [comment]
Does it work on 3.3.8?

**Comment by sethvargo** [comment]
Yea, 3.3.8 works fine

**Comment by sethvargo** [comment]
So does throwing a `require 'active_support/core_ext/module/attribute_accessors'` at the top.

**Comment by tdreyno** [comment]
@sethvargo Going to fix that and quickly release a new gem. Thanks!

**Comment by sethvargo** [comment]
:heart:

**Comment by tdreyno** [comment]
3.3.10 is out

**Comment by sethvargo** [comment]
Thank you very much!
