### ISSUE TITLE
Config errors when upgrading from 3.0.x to 3.1.x

### ISSUE THREAD

**Issue by ungoldman** [middleman/middleman#1003]
I have a large production site built with middleman that I'm attempting to upgrade from 3.0.13 to 3.1.4 to take advantage of the new features that have been added and I'm running into a lot of issues with middleman config settings apparently not having defaults.

I'm using ruby-1.9.3-p392 and hoping this isn't an issue with not using Ruby 2.

**(1) no more `settings` (not a big deal)**

```
middleman-core-3.1.4/lib/middleman-core/configuration.rb:133:in `method_missing': undefined method `markdown' for #<Middleman::Configuration::ConfigurationManager:0x007fbcdd34df18> (NoMethodError)
```

Got a `method_missing` leading me to have to change `settings.markdown` to `config[:markdown]` to access markdown settings. I'm guessing `settings` got dropped in favor of `config` which is understandable though not backwards compatible. However things got really hairy after that.

**(2) defaults aren't getting set (site breaking deal)**

```
middleman-core-3.1.4/lib/middleman-core/application.rb:193:in `join': can't convert nil into String (TypeError)
```

Digging in, I found `config[:source]` was `nil` for some reason, so I added `set :source, 'source'` to `config.rb`, thinking "Hmm, guess there's no longer a default source directory, that's weird, oh well." After that I got another one:

```
middleman-core-3.1.4/lib/middleman-core/core_extensions/file_watcher.rb:40:in `block in registered': undefined method `<<' for nil:NilClass (NoMethodError)
```

..leading me to believe `config[:file_watcher_ignore]` wasn't getting set even though line 32 of that same file had the following:

```
app.config.define_setting :file_watcher_ignore, IGNORE_LIST, 'Regexes for paths that should be ignored when they change.'
```

Now I'm starting to think something's wrong. I set `:file_watcher_ignore` manually in the config and run into the same problem with `:helpers_dir` and `:sass_assets_paths`. Since I'm not even using SASS/SCSS files external to the source directory I'm starting to think there's something quite broken.

So far the only way I've been able to start the server at all is by deleting the entire contents of `config.rb`. Help?
