### ISSUE TITLE
undefined method `run` for Middleman::PreviewServer:Class

### ISSUE THREAD

**Issue by anlek** [middleman/middleman#2126]
## Expected behaviour and actual behaviour
I was expecting to see my website. 
Actual Behaviour:
![image](https://user-images.githubusercontent.com/11052/32339050-cc4722c2-bfb3-11e7-8263-7e4ddc3e0320.png)

## Steps to reproduce the problem (from a clean middleman installation)
I'm using the latest code on GitHub as I need to be using the newest SASS version 3.5+ and the RubyGems version of middleman uses `compass-import-once` gem, and it is limiting `sass < 3.5`.

## Additional information

- Ruby version: ruby 2.4.1p111
- Middleman version: Middleman 4.2.1 (github.com code)
- OS version: OSX 10.12.6

**Comment by iwarner** [comment]
@AndrewKvalheim please provide a repo demonstrating this.

I am using the latest MM and on ruby 2.4.2 and have no issue.

**Comment by lotyrin** [comment]
Bisecting, this seems to have been introduced by 936d19cb

**Comment by lotyrin** [comment]
2.4.1 vs 2.4.2 doesn't seem to have anything to do with it.

**Comment by lotyrin** [comment]
Going through 936d19c diff line by line, it appears that [this change](https://github.com/middleman/middleman/commit/936d19cbb3567835fffc4e03abd32370167d688e#diff-651266bff1fe95df16385a564f875418L57) is involved.

Using contracts 0.14.0 or lower works, 0.15.0 or higher does not.

**Comment by lotyrin** [comment]
Narrowed it down to [this change](https://github.com/egonSchiele/contracts.ruby/commit/13e56bdf859a54c569d1a7fe4680251880c6d089#diff-a45dd775c2769b9ab16a23f9d4560adcL76) in contracts.

**Comment by anlek** [comment]
@lotyrin Thanking for tracking this down!
Is this something that needs to be fixed in Middleman or something I can fix on my end?

**Comment by lotyrin** [comment]
Something in Middleman or Contracts is wrong, but I'm not sure what yet. For now you can pin the version directly before 936d19c (12eb9ab), and the server runs.

I have yet to coax my IDE to let me place breakpoints inside Contracts from my reproduction case out in Middleman so I can figure out the callgraph where a PreviewServer has passed all the way to Contracts::CallWith's call_with_inner's blk (block) parameter...

**Comment by iwarner** [comment]
@anlek @lotyrin 
Hiya I always start my server with 

    NO_CONTRACTS=true bundle exec middleman server

So I was not seeing this error until today when I started a bit more manually - I would add this into your npm also

        "scripts": {
            "start": "NO_CONTRACTS=true bundle exec middleman server",

**Comment by salimane** [comment]
any update on this issue? yes there is a workaround, but is that the final fix ?

**Comment by johnnyshields** [comment]
Please make sure to fix this issue before releasing 4.3.0

**Comment by johnnyshields** [comment]
Raised a PR here: https://github.com/middleman/middleman/pull/2174

We should rollback contracts until the issue is fixed on their side.
