### ISSUE TITLE
Rack server support is broken

### ISSUE THREAD

**Issue by Domon** [middleman/middleman#1501]
# Steps to reproduce

1. Initialize a Middleman project with `middleman init --rack`.
2. Run any command to initialize a rack server, e.g. `rackup`, `puma`, ...

# Expected behavior

A rack server is up and running.

# Actual behavior

An error is raised: 

    NoMethodError: undefined method `server' for Middleman:Module

# Affected version

I found that this regression is caused by 14104aad70e9431d4891e835474efa7937b396a8, so the rack server support is broken in versions after that commit, i.e. `v3.3.9`,  `v3.3.10`.

**Comment by tdreyno** [comment]
Thanks for reporting, will investigate.

**Comment by inem** [comment]
It looks [like this](https://middlemanapp.com/basics/start-new-site#config-ru) no longer works again.

I've got the same `undefined method 'server' for Middleman:Module (NoMethodError)` with the fresh version of middleman.

My Gemfile:

```
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]

gem 'unicorn'
```
