### ISSUE TITLE
`wrap_layout` doesn't work with slim on ~> 3.3.2

### ISSUE THREAD

**Issue by darthdeus** [middleman/middleman#1269]
I've found this when I tried to create a new middleman site and did everything the same way I did with 3.0. Basically the problem is that when I create a layout that wraps the main `layout`, I'll get a `NoMethodError: undefined method 'safe_concat' for "":String` exception

Here's a whole stacktrace https://gist.github.com/darthdeus/fbd2662e754ddcccee3e

**I've also made a tiny middleman example reproducing this issue, see here https://github.com/darthdeus/middleman-slim-wrap-layout-bug**

**Comment by blackbiron** [comment]
experiencing same issue with middleman 3.3.7 & 3.3.10. cannot switch back to 3.0.0 (facing compatibility issues with foundation, sass & middleman-bower)

**Comment by tdreyno** [comment]
@blackbiron Please open a new issue with a test case.
